# Generated by Django 5.2.17 on 2026-09-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('customer_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField()),
                ('hour', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('merchant_category', models.CharField(max_length=100)),
                ('is_new_device', models.BooleanField(default=False)),
                ('device_id', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_fraud', models.BooleanField(default=False)),
                ('transaction_type', models.CharField(max_length=50)),
                ('card_present', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
