# Generated by Django 5.2.17 on 2026-09-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('fraud_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detection_time', models.DateTimeField()),
                ('fraud_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('investigator', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_age_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_log',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_ratio_to_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_ratio_to_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='avg_monthly_transactions',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='avg_transaction_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_avg_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_max_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_std_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_transaction_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device_fraud_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device_fraud_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device_total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location_fraud_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location_fraud_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location_total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location_x_encoded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location_y_encoded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_category_encoded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_score_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rolling_avg_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rolling_std_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='segment_encoded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type_encoded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_weekday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
