# Generated by Django 5.2.17 on 2026-09-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_transaction_account_age_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100, unique=True)),
                ('segment', models.CharField(max_length=100)),
                ('account_age_days', models.IntegerField()),
                ('risk_score', models.FloatField()),
                ('email_verified', models.BooleanField()),
                ('phone_verified', models.BooleanField()),
                ('avg_monthly_transactions', models.FloatField()),
                ('avg_transaction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('device_count', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
