# Generated by Django 5.2.17 on 2026-09-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
